### ISSUE TITLE
Support Express set View Engine

### ISSUE THREAD

**Issue by hmexx** [futureaus/servue#21]
Hey dude.

Nice library. I've started using it as an alternative to nunjucks for templating.

One nice-to-have would be to make it work as a standard Express view engine. Then you could just call render() on .vue files instead of calling the renderer directly. Not a big deal tho. Works fine as is.

https://expressjs.com/en/guide/using-template-engines.html

**Comment by DominusVilicus** [comment]
I've done something like this for my Koa app:
```js
    var servue = new Servue()
    app.use(async (ctx, next) => {
        /**
         * render returns promise to the string which contians the rendered .vue file
         * @param {string} vueFile - path to vue single-file-component
         * @param {Object=} [data={}] - data to be inserted into .vue file when generating renderer
         * @returns {Promise<string>}
         */
        ctx.render = async(vueFile, data) => {
            ctx.body = await servue.render(vueFile, data)
        }
    
        await next()
    })
```

You can do something similar with express pretty easily

**Comment by hmexx** [comment]
Thanks for the code sample. I'll give it a shot.
