### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by nick-fytros** [futureaus/servue#25]
Hello,

I want to start by saying your package looks very interesting.
I created a sample project in order to try the expressjs setup and after installing the base packages I got the errors below:

- `error on start Error: Cannot find module 'vue-server-renderer'`

- `vue-template-compiler must be installed as a peer dependency`

and some errors on no closing tags on the `slots` in the template part but I intend on opening a PR to fix some examples.
Is it required on purpose to install `vue-server-renderer`, `vue-template-compiler` and `vue` in our project and so they are not included in the package? If so that needs to be added to the docs.

**Comment by DominusVilicus** [comment]
That's correct, they are peer-dependencies. I made it that way so that users can control their Vue version.
 
I should probably ad that to the docs.

**Comment by DominusVilicus** [comment]
Fixed with 034d530
