### ISSUE TITLE
Vuex support?

### ISSUE THREAD

**Issue by slidenerd** [futureaus/servue#27]
- Hi, first of all fantastic efforts with this library. I saw that you forked and heavily modified this from express-vue
- Express-Vue has one limitation in that it doesnt support Vuex as discussed [HERE](https://github.com/express-vue/express-vue/issues/178)
- Your documentation makes no reference to Vuex hence the issue

**Comment by DominusVilicus** [comment]
@slidenerd i'm going to be building a very different server-side renderer. I've realised vuex fits with the way vue works when using templating, global variables and server-side rendering

the new server-side renderer will be less CPU and memory intensive, and will involve some extra routing for build files.

The new server-side renderer will support vuex.
