### ISSUE TITLE
Will you continue to update & support this package?

### ISSUE THREAD

**Issue by JaroslavPrt** [futureaus/servue#6]

**Comment by DominusVilicus** [comment]
I will continue to support this package and am already using it in various projects. I have an incentive to update it.

The package remains stable currently and is production ready for small-medium sites.

I will be adding features throughout time depending if `vue-server-renderer` adds any features to their package. I may release major versions with breaking changes if needed but likely won't provide any LTS (long term support) for older versions if major goes up. I will provide upgrade guides if I ever do update the major version

It would be great to see some users using this, and happy to provide support & answer questions.

**Comment by DominusVilicus** [comment]
Will leave this open for any future users to have a read

**Comment by DominusVilicus** [comment]
Closed, but `pinned` this issue so people can see
