### ISSUE TITLE
Load vue from cdn instead paste to page code

### ISSUE THREAD

**Issue by Satont** [futureaus/servue#8]
As i see you paste vue.js via <script> </script> to page code.
Can you please replace it by <script src="vue cdn"></script>?
It will be more readble.
Or if you not want load vue from external site, maybe add possible add something like option
servue.loadvue: locally/cdn
i will be very approdicated :)

**Comment by DominusVilicus** [comment]
So to clarify, the `vue` is imported from the `node_modues/vue/dist/build.js` folder by webpack
